### ISSUE TITLE
"Cannot add a bridged Accessory with the same UUID as another bridged Accessory"

### ISSUE THREAD

**Issue by BjornEricsson** [va-lemon/homebridge-neeo#1]
Trying to install on my Mac. Something goes wrong, but I can't figure out what. A side note: Are the scenes needed in config anymore? I see that they are found anyhow.

--------------HomeBridge adapter-------------
[2017-12-31 14:33:37] Loaded plugin: homebridge-neeo
[2017-12-31 14:33:37] Registering platform 'homebridge-neeo.Neeo'
[2017-12-31 14:33:37] ---
[2017-12-31 14:33:37] Loaded plugin: homebridge-websocket
homebridge API version: 2.2
[2017-12-31 14:33:37] Registering platform 'homebridge-websocket.websocket'
[2017-12-31 14:33:37] ---
[2017-12-31 14:33:37] Loaded config.json with 0 accessories and 2 platforms.
[2017-12-31 14:33:37] ---
[2017-12-31 14:33:37] Loading 2 platforms...
[2017-12-31 14:33:37] [websocket] Initializing websocket platform...
[2017-12-31 14:33:37] [websocket] homebridge-websocket v0.1.13
[2017-12-31 14:33:37] [Neeo] Initializing Neeo platform...
NEEO - use NEEO Brain IP from env variable NEEO-XXXXXXXX.local
NEEO - Start HomeBridge Driver
[2017-12-31 14:33:37] [Neeo] Create 0 NEEO buttons in HomeKit for 0 scenes
[2017-12-31 14:33:37] [Neeo] Fetching Neeo Recipes...
[2017-12-31 14:33:37] [websocket] Plugin - DidFinishLaunching
[2017-12-31 14:33:37] [websocket] Number of Accessories: 1
[2017-12-31 14:33:37] [websocket] url {"address":"::","family":"IPv6","port":4050}
[2017-12-31 14:33:38] [websocket] on.close client ip undefined disconnected
[2017-12-31 14:33:38] [websocket] client ip undefined connected
NEEO READY! use the NEEO app to search for "HomeKit Buttons".
[2017-12-31 14:33:43] [Neeo] Retrieved 9 recipes from NEEO Brain
[2017-12-31 14:33:43] [Neeo] Adding Accessory: Apple TV
[2017-12-31 14:33:43] [Neeo] Created Apple TV Accessory
[2017-12-31 14:33:43] [Neeo] Adding Accessory: TV
[2017-12-31 14:33:43] [Neeo] Created TV Accessory
[2017-12-31 14:33:43] [Neeo] Adding Accessory: PlayStation
[2017-12-31 14:33:43] [Neeo] Created PlayStation Accessory
[2017-12-31 14:33:43] [Neeo] Adding Accessory: Radio
[2017-12-31 14:33:43] [Neeo] Created Radio Accessory
[2017-12-31 14:33:43] [Neeo] Adding Accessory: Disc
[2017-12-31 14:33:43] [Neeo] Created Disc Accessory
[2017-12-31 14:33:43] [Neeo] Adding Accessory: LIGHT
[2017-12-31 14:33:43] [Neeo] Created LIGHT Accessory
[2017-12-31 14:33:43] [Neeo] Adding Accessory: Apple TV%20Ljud
[2017-12-31 14:33:43] [Neeo] Created Apple TV%20Ljud Accessory
[2017-12-31 14:33:43] [Neeo] Adding Accessory: LIGHT
[2017-12-31 14:33:43] [Neeo] Created LIGHT Accessory
[2017-12-31 14:33:43] [Neeo] Adding Accessory: Hall belysning-on
[2017-12-31 14:33:43] [Neeo] Created Hall belysning-on Accessory
[2017-12-31 14:33:43] [Neeo] Returning 9 accessories
[2017-12-31 14:33:43] [Neeo] Initializing platform accessory 'Apple TV'...
Adding switch services
[2017-12-31 14:33:43] [Neeo] Initializing platform accessory 'TV'...
Adding switch services
[2017-12-31 14:33:43] [Neeo] Initializing platform accessory 'PlayStation'...
Adding switch services
[2017-12-31 14:33:43] [Neeo] Initializing platform accessory 'Radio'...
Adding switch services
[2017-12-31 14:33:43] [Neeo] Initializing platform accessory 'Disc'...
Adding switch services
[2017-12-31 14:33:43] [Neeo] Initializing platform accessory 'LIGHT'...
Adding switch services
[2017-12-31 14:33:43] [Neeo] Initializing platform accessory 'Apple TV%20Ljud'...
Adding switch services
[2017-12-31 14:33:43] [Neeo] Initializing platform accessory 'LIGHT'...
Adding switch services
/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:258
      throw new Error("Cannot add a bridged Accessory with the same UUID as another bridged Accessory: " + existing.UUID);
Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: f7d46fe5-4bcb-4d98-91ab-068752b026c0
    at Bridge.Accessory.addBridgedAccessory (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:258:13)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:377:24)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:16:19
    at /usr/local/lib/node_modules/homebridge-neeo/index.js:167:7
    at Request._callback (/usr/local/lib/node_modules/homebridge-neeo/index.js:73:5)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-neeo/node_modules/request/request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-neeo/node_modules/request/request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-neeo/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)

**Comment by BjornEricsson** [comment]
With further googling I found that other plugins have the same problem if devices have the same name. So I tried to disable one of the LIGHT devices that Neeo names automatically, and now I have no problem. Maybe LIGHT devices should be renamed when fetched from the brain?
