### ISSUE TITLE
Not pulling in Homekit Scenes.

### ISSUE THREAD

**Issue by realdannys** [va-lemon/homebridge-neeo#2]
I can't get Neeo to loads the scenes I tell it to. My config is like this.

`{
            "platform": "Neeo",
            "neeoBrain": "NEEO-299ea1ee",
            "scenes": [
                {
                    "name": "Good Night",
                    "label": "Good Night"
                },
                {
                    "name": "Read",
                    "label": "Read"
                },
                {
                    "name": "Relax",
                    "label": "Relax"
                }
            ]
        }`

But in the Neeo app it shows random scenes under the accessory button I don't even have.

"Bedtime, Dinner Time, Evening, Watch TV" etc.

Any ideas?

**Comment by realdannys** [comment]
Ah realised I needed to updated the index.js too, which I have now - but now when I try to trigger a short I get the following error in console from websocket.

`/usr/local/lib/node_modules/homebridge-websocket/lib/websocket.js:71
  var msg = JSON.parse(data);
                 ^
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Websocket.onMessage (/usr/local/lib/node_modules/homebridge-websocket/lib/websocket.js:71:18)
    at Websocket.message (/usr/local/lib/node_modules/homebridge-websocket/lib/websocket.js:51:12)
    at emitTwo (events.js:125:13)
    at WebSocket.emit (events.js:213:7)
    at Receiver.onbinary (/usr/local/lib/node_modules/homebridge-websocket/node_modules/ws/lib/WebSocket.js:823:10)
    at /usr/local/lib/node_modules/homebridge-websocket/node_modules/ws/lib/Receiver.js:537:18
    at Receiver.applyExtensions (/usr/local/lib/node_modules/homebridge-websocket/node_modules/ws/lib/Receiver.js:364:5)
    at /usr/local/lib/node_modules/homebridge-websocket/node_modules/ws/lib/Receiver.js:531:14
    at Receiver.flush (/usr/local/lib/node_modules/homebridge-websocket/node_modules/ws/lib/Receiver.js:340:3)
    at Receiver.finish (/usr/local/lib/node_modules/homebridge-websocket/node_modules/ws/lib/Receiver.js:542:12)
    at /usr/local/lib/node_modules/homebridge-websocket/node_modules/ws/lib/Receiver.js:516:33
    at Receiver.expectData (/usr/local/lib/node_modules/homebridge-websocket/node_modules/ws/lib/Receiver.js:155:5)
    at Receiver.expectHandler (/usr/local/lib/node_modules/homebridge-websocket/node_modules/ws/lib/Receiver.js:515:16)
    at Receiver.add (/usr/local/lib/node_modules/homebridge-websocket/node_modules/ws/lib/Receiver.js:95:24)
    at Socket.realHandler (/usr/local/lib/node_modules/homebridge-websocket/node_modules/ws/lib/WebSocket.js:800:20)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:266:12)
    at readableAddChunk (_stream_readable.js:253:11)
    at Socket.Readable.push (_stream_readable.js:211:10)
    at TCP.onread (net.js:585:20)`
